package myBatis.entity;

/**
 * 数据表{department}的实体类
 *
 * 此类是由MyBatis Generator生成的。
 * 此类对应于数据库表 department
 */
public class Department {
    /**
     * 数据表{department}中的{deptid}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 department.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer deptid;

    /**
     * 数据表{department}中的{name}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 department.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptid
     *
     * @return the value of department.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptid
     *
     * @param deptid the value for department.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}