package myBatis.entity;

/**
 * 数据表{worker}的实体类
 *
 * 此类是由MyBatis Generator生成的。
 * 此类对应于数据库表 worker
 */
public class Worker {
    /**
     * 数据表{worker}中的{id}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.id
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer id;

    /**
     * 数据表{worker}中的{name}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private String name;

    /**
     * 数据表{worker}中的{pthone}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.pthone
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer pthone;

    /**
     * 数据表{worker}中的{salary}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.salary
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer salary;

    /**
     * 数据表{worker}中的{absence}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.absence
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer absence;

    /**
     * 数据表{worker}中的{deptid}字段
     *
     * 该字段由MyBatis Generator生成。
     * 该字段对应于数据库列。 worker.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.id
     *
     * @return the value of worker.id
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.id
     *
     * @param id the value for worker.id
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.pthone
     *
     * @return the value of worker.pthone
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getPthone() {
        return pthone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.pthone
     *
     * @param pthone the value for worker.pthone
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setPthone(Integer pthone) {
        this.pthone = pthone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.salary
     *
     * @return the value of worker.salary
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.salary
     *
     * @param salary the value for worker.salary
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.absence
     *
     * @return the value of worker.absence
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getAbsence() {
        return absence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.absence
     *
     * @param absence the value for worker.absence
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setAbsence(Integer absence) {
        this.absence = absence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.deptid
     *
     * @return the value of worker.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.deptid
     *
     * @param deptid the value for worker.deptid
     *
     * @mbg.generated Thu Oct 17 15:47:09 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}